/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import convertidormultibase.*;
import McQuinnator.*;
import Automatizador.*;
import java.awt.event.KeyEvent;
import java.util.logging.*;

/**
 *
 * @author esteban
 */
public class JFrameStarterPack extends javax.swing.JFrame {

    private final Calculadora calculadora;
    private Fase2 fase2;
    private int tablaActual = 0;
    
    /**
     * Creates new form JFrameStarterPack
     */
    public JFrameStarterPack() {
        this.calculadora = new Calculadora();
        this.fase2 = null;
        initComponents();
        this.Error.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Numero1 = new javax.swing.JTextField();
        baseNumero1 = new javax.swing.JTextField();
        Numero2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        baseNumero2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ComboBoxProcedimiento = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        Destino = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        valorResultado = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        Error = new javax.swing.JLabel();
        ingresar = new javax.swing.JButton();
        calcular = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaTabla = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        Entrada = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        FuncionAnterior = new javax.swing.JTextField();
        CantidadTablas = new javax.swing.JLabel();
        NumeroTabla = new javax.swing.JLabel();
        Izquierda = new javax.swing.JButton();
        BotonTPrimosColapsados = new javax.swing.JButton();
        Derecha = new javax.swing.JButton();
        BotonTPrimosNoColapsados = new javax.swing.JButton();
        Creador = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSpinnerBase = new javax.swing.JSpinner();
        jSpinnerDivisor = new javax.swing.JSpinner();
        jScrollPane3 = new javax.swing.JScrollPane();
        TextAreaTransiciones = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        Transiciones = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("F0C Starter Pack");

        jTabbedPane1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPanel1KeyTyped(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Primer Número");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Segundo Número");

        Numero1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Numero1KeyTyped(evt);
            }
        });

        baseNumero1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                baseNumero1KeyTyped(evt);
            }
        });

        Numero2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Numero2KeyTyped(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Base del Primer Número");

        baseNumero2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                baseNumero2KeyTyped(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Base del Segundo Número");

        ComboBoxProcedimiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Conversion", "Suma", "Resta", "Division", "Residuo", "Multiplicacion", "Potencia", "Logaritmo", "MaximaCapacidadBase" }));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Base del Destino");

        Destino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DestinoKeyTyped(evt);
            }
        });

        valorResultado.setEditable(false);
        valorResultado.setColumns(20);
        valorResultado.setRows(5);
        jScrollPane2.setViewportView(valorResultado);

        jLabel8.setText("Resultado");

        Error.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Error.setText("Por favor, ingrese datos válidos");

        ingresar.setText("Ingresar");
        ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarActionPerformed(evt);
            }
        });

        calcular.setText("Calcular");
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });

        limpiar.setText("Limpiar Datos");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/F0C Info.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                            .addComponent(baseNumero1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Destino, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComboBoxProcedimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(149, 149, 149)
                                        .addComponent(baseNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(103, 103, 103)
                                        .addComponent(Numero2)))
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                                    .addComponent(Numero1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(limpiar)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ingresar)
                                            .addComponent(calcular)
                                            .addComponent(Error, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)))
                                    .addComponent(jLabel9)))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Numero1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Numero2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxProcedimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(baseNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(baseNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Destino, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(Error, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ingresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calcular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(limpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Omnibaser", jPanel1);

        TextAreaTabla.setEditable(false);
        TextAreaTabla.setColumns(20);
        TextAreaTabla.setRows(5);
        jScrollPane1.setViewportView(TextAreaTabla);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Ingrese la función: ");

        Entrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EntradaKeyTyped(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("E<b>:(<Términos>)");

        FuncionAnterior.setEditable(false);
        FuncionAnterior.setText("Aquí estará la función ingresada anteriormente");

        CantidadTablas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CantidadTablas.setText("Cantidad de Tablas: ");

        NumeroTabla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NumeroTabla.setText("Tabla: ");

        Izquierda.setText("Tabla Anterior");
        Izquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IzquierdaActionPerformed(evt);
            }
        });

        BotonTPrimosColapsados.setText("Mostrar/Ocultar Primos Colapsados");
        BotonTPrimosColapsados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonTPrimosColapsadosActionPerformed(evt);
            }
        });

        Derecha.setText("Tabla Siguiente");
        Derecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DerechaActionPerformed(evt);
            }
        });

        BotonTPrimosNoColapsados.setText("Mostrar/Ocultar Primos No Colapsados");
        BotonTPrimosNoColapsados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonTPrimosNoColapsadosActionPerformed(evt);
            }
        });

        Creador.setText("Hacer Tablas");
        Creador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreadorActionPerformed(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/F0C Info.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Izquierda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BotonTPrimosColapsados, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)))
                            .addComponent(CantidadTablas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NumeroTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BotonTPrimosNoColapsados)
                            .addComponent(Derecha, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Entrada)
                                    .addComponent(FuncionAnterior))
                                .addGap(12, 12, 12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Creador, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Entrada, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FuncionAnterior, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Creador, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel14))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(Derecha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BotonTPrimosNoColapsados)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(Izquierda)
                        .addGap(18, 18, 18)
                        .addComponent(BotonTPrimosColapsados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 359, Short.MAX_VALUE)
                        .addComponent(NumeroTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CantidadTablas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("McQuinnator", jPanel2);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Ingrese la base que desea dividir");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Ingrese el divisor");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Ingrese los datos del autómata");

        jSpinnerBase.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jSpinnerDivisor.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        TextAreaTransiciones.setColumns(20);
        TextAreaTransiciones.setRows(5);
        jScrollPane3.setViewportView(TextAreaTransiciones);

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setText("Transiciones del Autómata");

        Transiciones.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Transiciones.setText("Calcular Transiciones");
        Transiciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransicionesActionPerformed(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/F0C Info.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(655, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(380, 380, 380))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSpinnerBase)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                            .addComponent(jSpinnerDivisor)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Transiciones, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSpinnerBase, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(jSpinnerDivisor))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Transiciones, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 381, Short.MAX_VALUE)
                        .addComponent(jLabel15)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Automatizador", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1KeyTyped

    private void ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarActionPerformed
        // TODO add your handling code here:
        //si se desea calcular el máximo dígito para una base, entra aquí, pues no necesita operandos, sólo el destino
        if(this.ComboBoxProcedimiento.getSelectedItem().toString().equals("MaximaCapacidadBase") && !this.Destino.getText().equals("")){
            try{
                this.calculadora.ingresarProcedimiento(Procedimiento.MaximaCapacidadBase,null, null, Integer.parseInt(this.Destino.getText()));
                Error.setVisible(false);
            }catch(NumberFormatException exc){
                Logger.getLogger(Calculadora.class.getName()).log(Level.SEVERE, null, exc);
                this.Error.setVisible(true);
                this.valorResultado.setText("");
            }
            return;
            
        }
        //si la operación deseada era de conversión, sólo se necesita un operando   
        System.out.println(this.ComboBoxProcedimiento.getSelectedItem().toString());
        if(this.ComboBoxProcedimiento.getSelectedItem().toString().equals("Conversion") && !this.Numero1.getText().equals("") && !this.baseNumero2.getText().equals("") && this.baseNumero2.getText().equals("") && this.Numero2.getText().equals("")){
            try{
                this.calculadora.ingresarProcedimiento(Procedimiento.Conversion, new Numero(Integer.parseInt(this.baseNumero1.getText()),this.Numero1.getText()), null, Integer.parseInt(Destino.getText()));
                Error.setVisible(false);
            }catch(DigitOutOfBaseBoundsException | NumberFormatException exc){
                Logger.getLogger(Calculadora.class.getName()).log(Level.SEVERE, null, exc);
                this.Error.setVisible(true);
                this.valorResultado.setText("");
            }
            return;
        }
        //si llega hasta aquí significa que la operación deseada sí necesita ambos operandos
        try{
            //ingresa la información de los labels a la calculadora
            this.calculadora.ingresarProcedimiento(Procedimiento.valueOf(this.ComboBoxProcedimiento.getSelectedItem().toString()), new Numero(Integer.parseInt(baseNumero1.getText()),Numero1.getText()), new Numero(Integer.parseInt(baseNumero2.getText()),Numero2.getText()), Integer.parseInt(Destino.getText()));
            Error.setVisible(false);
        }catch(DigitOutOfBaseBoundsException | NumberFormatException ex){//este es que el usuario se cagó en el sistema
            Logger.getLogger(Calculadora.class.getName()).log(Level.SEVERE, null, ex);
            //hace visible el label en caso de que el usuario ingrese una idiotez jaja
            this.Error.setVisible(true);
            this.valorResultado.setText("");
        }
    }//GEN-LAST:event_ingresarActionPerformed

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        // TODO add your handling code here:
        this.valorResultado.setText(this.calculadora.realizarProcedimiento());
        if(!this.Numero2.getText().equals("")){
            try{
                int cuentaDigitos = Integer.parseInt(this.Numero2.getText());
                String nuevoStr = this.valorResultado.getText();
                while(nuevoStr.length() < cuentaDigitos){
                    nuevoStr = "0".concat(nuevoStr);
                }
                this.valorResultado.setText(nuevoStr);
            }catch(NumberFormatException exc){
                this.Error.setVisible(true);
            }
        }
    }//GEN-LAST:event_calcularActionPerformed

    private void CreadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreadorActionPerformed
        // TODO add your handling code here:
        try{
            this.fase2 = new Fase2(this.Entrada.getText());
            //this.fase2.getFase1AProcesar().hacerTablas(); //legado de la vieja interfaz
            this.tablaActual = 0;
            this.TextAreaTabla.setText(this.fase2.getFase1AProcesar().getTablas().get(this.tablaActual).toString());
            this.FuncionAnterior.setText(this.Entrada.getText().trim());
            this.NumeroTabla.setText("Tabla: " + (this.tablaActual+1));
            this.CantidadTablas.setText("Cantidad de Tablas: " + this.fase2.getFase1AProcesar().getTablas().size());
        }catch(Exception exc){
            this.Error.setVisible(true);
            this.TextAreaTabla.setText("");
        }
    }//GEN-LAST:event_CreadorActionPerformed

    private void IzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IzquierdaActionPerformed
        // TODO add your handling code here:
        if(this.fase2 != null && this.tablaActual > 0){
            this.tablaActual--;
            this.TextAreaTabla.setText(this.fase2.getFase1AProcesar().getTablas().get(this.tablaActual).toString());
            this.NumeroTabla.setText("Tabla: " + (this.tablaActual+1));
        }
    }//GEN-LAST:event_IzquierdaActionPerformed

    private void DerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DerechaActionPerformed
        // TODO add your handling code here:
        if(this.fase2 != null && this.tablaActual < this.fase2.getFase1AProcesar().getTablas().size()-1){
            this.tablaActual++;
            this.TextAreaTabla.setText(this.fase2.getFase1AProcesar().getTablas().get(this.tablaActual).toString());
            this.NumeroTabla.setText("Tabla: " + (this.tablaActual+1));
        }
    }//GEN-LAST:event_DerechaActionPerformed

    private void BotonTPrimosColapsadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonTPrimosColapsadosActionPerformed
        // TODO add your handling code here:
        if(this.fase2 != null){
            if(this.tablaActual != -1){
                this.TextAreaTabla.setText(this.fase2.getTablaEsenciales().mostrarPrimosString());
                this.tablaActual = -1;
            }
            else{
                this.tablaActual = 0;
                this.TextAreaTabla.setText(this.fase2.getFase1AProcesar().getTablas().get(this.tablaActual).toString());
            }
        }
    }//GEN-LAST:event_BotonTPrimosColapsadosActionPerformed

    private void BotonTPrimosNoColapsadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonTPrimosNoColapsadosActionPerformed
        // TODO add your handling code here:
        if(this.fase2 != null){
            if(this.tablaActual != -2){
                this.TextAreaTabla.setText(this.fase2.getTablaEsenciales().mostrarPrimosNoColapsadosString());
                this.tablaActual = -2;
            }
            else{
                this.tablaActual = 0;
                this.TextAreaTabla.setText(this.fase2.getFase1AProcesar().getTablas().get(this.tablaActual).toString());
            }
        }
    }//GEN-LAST:event_BotonTPrimosNoColapsadosActionPerformed

    private void TransicionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransicionesActionPerformed
        try {
            // TODO add your handling code here:
            Automatizador automatizador = new Automatizador((int)this.jSpinnerBase.getValue(), (int)this.jSpinnerDivisor.getValue());
            this.TextAreaTransiciones.setText(automatizador.toString());
        } catch (NonExistantBaseException ex) {
            java.util.logging.Logger.getLogger(JFrameStarterPack.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_TransicionesActionPerformed

    private void EntradaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EntradaKeyTyped
        // TODO add your handling code here:
        char capturaTecla = evt.getKeyChar();
        
        if(capturaTecla == KeyEvent.VK_ENTER){
            this.Creador.doClick();
        }
    }//GEN-LAST:event_EntradaKeyTyped

    private void baseNumero2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_baseNumero2KeyTyped
        // TODO add your handling code here:
        char capturaTecla = evt.getKeyChar();
        
        if(capturaTecla == KeyEvent.VK_ENTER){
            this.ingresar.doClick();
            this.calcular.doClick();
        }
        else{
            if(capturaTecla == KeyEvent.VK_DELETE){
                this.limpiar.doClick();
            }
        }
        
    }//GEN-LAST:event_baseNumero2KeyTyped

    private void Numero1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Numero1KeyTyped
        // TODO add your handling code here:
        char capturaTecla = evt.getKeyChar();
        
        if(capturaTecla == KeyEvent.VK_ENTER){
            this.ingresar.doClick();
            this.calcular.doClick();
        }
        else{
            if(capturaTecla == KeyEvent.VK_DELETE){
                this.limpiar.doClick();
            }
        }
    }//GEN-LAST:event_Numero1KeyTyped

    private void baseNumero1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_baseNumero1KeyTyped
        // TODO add your handling code here:
        char capturaTecla = evt.getKeyChar();
        
        if(capturaTecla == KeyEvent.VK_ENTER){
            this.ingresar.doClick();
            this.calcular.doClick();
        }
        else{
            if(capturaTecla == KeyEvent.VK_DELETE){
                this.limpiar.doClick();
            }
        }
    }//GEN-LAST:event_baseNumero1KeyTyped

    private void DestinoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DestinoKeyTyped
        // TODO add your handling code here:
        char capturaTecla = evt.getKeyChar();
        
        if(capturaTecla == KeyEvent.VK_ENTER){
            this.ingresar.doClick();
            this.calcular.doClick();
        }
        else{
            if(capturaTecla == KeyEvent.VK_DELETE){
                this.limpiar.doClick();
            }
        }
    }//GEN-LAST:event_DestinoKeyTyped

    private void Numero2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Numero2KeyTyped
        // TODO add your handling code here:
        char capturaTecla = evt.getKeyChar();
        
        if(capturaTecla == KeyEvent.VK_ENTER){
            this.ingresar.doClick();
            this.calcular.doClick();
        }
        else{
            if(capturaTecla == KeyEvent.VK_DELETE){
                this.limpiar.doClick();
            }
        }
    }//GEN-LAST:event_Numero2KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        if(false)
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) { 
            java.util.logging.Logger.getLogger(JFrameStarterPack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameStarterPack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameStarterPack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameStarterPack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameStarterPack().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonTPrimosColapsados;
    private javax.swing.JButton BotonTPrimosNoColapsados;
    private javax.swing.JLabel CantidadTablas;
    private javax.swing.JComboBox<String> ComboBoxProcedimiento;
    private javax.swing.JButton Creador;
    private javax.swing.JButton Derecha;
    private javax.swing.JTextField Destino;
    private javax.swing.JTextField Entrada;
    private javax.swing.JLabel Error;
    private javax.swing.JTextField FuncionAnterior;
    private javax.swing.JButton Izquierda;
    private javax.swing.JTextField Numero1;
    private javax.swing.JTextField Numero2;
    private javax.swing.JLabel NumeroTabla;
    private javax.swing.JTextArea TextAreaTabla;
    private javax.swing.JTextArea TextAreaTransiciones;
    private javax.swing.JButton Transiciones;
    private javax.swing.JTextField baseNumero1;
    private javax.swing.JTextField baseNumero2;
    private javax.swing.JButton calcular;
    private javax.swing.JButton ingresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinnerBase;
    private javax.swing.JSpinner jSpinnerDivisor;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton limpiar;
    private javax.swing.JTextArea valorResultado;
    // End of variables declaration//GEN-END:variables
}
